### ISSUE TITLE
User sessions are broken

### ISSUE THREAD

**Issue by akiva** [vodik/envoy#35]
I am trying to run envoy as a user unit session, since I wish to set my GPG homedir to a custom path and not force it upon all users of my system. Something similar was discussed here: <https://github.com/vodik/envoy/issues/7>. However, dbus causes issues with this.

**Comment by vodik** [comment]
Hey, so I've looked over this and its not an envoy bug :grinning:

DBus and user sessions are sorta murky in the short term - at least until kdbus lands. Then pam is supposedly going to take the responsibility of setting up the user dbus session properly.

1. https://wiki.archlinux.org/index.php/Systemd/User#D-Bus - follow the instructions here to setup dbus in the systemd user session.
2. Make sure you set `Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/%U/dbus/user_bus_socket` in the user service file:

```
[Unit]
Description=Envoy agent monitor for %i
Documentation=man:envoyd(1) man:envoy(1)

[Service]
ExecStart=/usr/bin/envoyd -t %i
StandardOutput=syslog
StandardError=syslog
Environment=GNUPGHOME=/path/to/home
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/%U/dbus/user_bus_socket

[Install]
WantedBy=multi-user.target
Also=envoy@.socket
```

Should do the trick. Give it a shot.

**Comment by vodik** [comment]
Please reopen if there are any other issues.

**Comment by akiva** [comment]
vodik, I will update you when I get a chance to look into this again. For now, I have simply simlinked my `~/.config/gnupg` to `~/.gnupg`. Thanks again.

**Comment by vodik** [comment]
Yeah, I'm going to declare user sessions unsupported until all the dbus/kdbus stuff settles down.

**Comment by vodik** [comment]
@akiva So I've ported envoy to sd-bus. User sessions should be functional again. I don't know if you care at this stage anymore, but though I'd follow up:

~~~c
$ systemctl status --user envoy-gpg-agent-monitor-1000.scope 
● envoy-gpg-agent-monitor-1000.scope - Envoy agent monitoring scope
   Loaded: loaded (/home/simon/.config/systemd/user/envoy-gpg-agent-monitor-1000.scope; static)
  Drop-In: /home/simon/etc/systemd/user/envoy-gpg-agent-monitor-1000.scope.d
           └─90-Description.conf, 90-Slice.conf
   Active: active (running) since Sun 2015-06-28 15:41:53 EDT; 4min 36s ago
   CGroup: /user.slice/user-1000.slice/user@1000.service/envoy.slice/envoy-gpg-agent-monitor-1000.scope
           └─2305 /usr/bin/gpg-agent --daemon --enable-ssh-support

Jun 28 15:41:53 nesasio systemd[352]: Started Envoy agent monitoring scope.
~~~

**Comment by vodik** [comment]
Okay, still some issues, follow #47 for this.
