### ISSUE TITLE
pam_envoy doesn't unlock

### ISSUE THREAD

**Issue by ramonmaruko** [vodik/envoy#40]
Relevant lines in the `journalctl`. I edited `pam_envoy.c` to display `data.status` and `data.type`.
`envoy@gpg-agent.socket` is already enabled.

```
Mar 20 12:37:31 athena envoyd[286]: Starting gpg-agent for uid=1000.
Mar 20 12:37:31 athena lightdm[642]: pam-envoy: status: 1 type: 1
Mar 20 12:37:31 athena lightdm[642]: pam-envoy: expected status: 2 type: 1
Mar 20 12:37:31 athena lightdm[293]: ** (process:642): WARNING **: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
Mar 20 12:37:31 athena lightdm[616]: pam_unix(lightdm-greeter:session): session closed for user lightdm
Mar 20 12:37:31 athena lightdm[642]: pam_unix(lightdm:session): session opened for user marco by (uid=0)
Mar 20 12:37:31 athena systemd-logind[292]: New session c2 of user marco.
Mar 20 12:37:31 athena systemd[649]: pam_unix(systemd-user:session): session opened for user marco by (uid=0)

```

**Comment by ramonmaruko** [comment]
Changing the checking of `data.status` from `ENVOY_RUNNING` to `ENVOY_STARTED` made it unlock on login. This is on a system running Arch Linux.

**Comment by vodik** [comment]
Oh, I think I know what the logic problem is then, good catch!

The `ENVOY_STARTED` state is this special state that means that the agent its running, but only part of the "startup" process ran, just enough to get environment. This is so that the pam module and envoy-exec can both properly inject the environment but not break the envoy's key adding logic when that command is run.

Yeah, so I need to fix up the status logic and test things a bit more thoroughly :frowning:. The mistake I made here is testing the pam module without doing a fresh reboot.
