### ISSUE TITLE
Keep same environment with PAM / act as proxy for agent

### ISSUE THREAD

**Issue by blueyed** [vodik/envoy#51]
I am using the PAM module, and it seems that (at least) `envoy --kill` will result in the environment to become out of date.

Would it be possible for envoy to wrap the agent (I am using `gpg-agent` currently), so that killing and restarting it would not require you to use `eval "$(envoy -p)"` to update the environment to the new one?
E.g. by making envoy manage the sockets and act as a proxy to the real agent?

I know that I have used `envoy --kill` while I really wanted `envoy --expunge` instead, but it made me wonder.

I am using this in `/etc/pam.d/common-session` on Ubuntu:

    session   optional    pam_envoy.so gpg-agent

**Comment by vodik** [comment]
I have considered doing this, but always thought I'd rather just write my own agent. I do thing the gnome-keyring approach is saner... I'm just waiting for sd-bus to stabilize a bit.

Adding a proxy isn't so useful because that's only part of the problem. For a complete solution you need to tell gpg-agent where to launch the pinentry as well. For more technical details, I have a good writeup [here][writeup]. For these reasons, I don't really recommend the pam module for gpg-agent support (and I don't personally use it unless I need to use ssh-agent).

So with that out of the way, I do have proxy, just at a different layer. `envoy-exec` is there to make sure that when we run a command that cares about the agent its both running and that the pinentry will popup in the right place.

I have some wrappers setup with envoy-exec and no pam integration and gpg-agent just does the right stuff when I need it. I can tolerate a `envoy --kill` just fine.

  [writeup]: https://github.com/vodik/envoy/issues/37#issuecomment-87529974
